In [6]:
import pandas as pd
import string
df=pd.read_csv('Twitter Sentiments.csv')

In [7]:
df.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [8]:
df=df.drop(columns=['id','label'], axis=1)

In [9]:
df.head()

                                               tweet
0   @user when a father is dysfunctional and is s...
1  @user @user thanks for #lyft credit i can't us...
2                                bihday your majesty
3  #model   i love u take with u all the time in ...
4             factsguide: society now    #motivation

In [10]:
df['clean_text']=df['tweet'].str.lower()

In [11]:
df.head()

,tweet,clean_text
0,@user when a father is dysfunctional and is s...,@user when a father is dysfunctional and is s...
1,@user @user thanks for #lyft credit i can't us...,@user @user thanks for #lyft credit i can't us...
2,bihday your majesty,bihday your majesty
3,#model i love u take with u all the time in ...,#model i love u take with u all the time in ...
4,factsguide: society now #motivation,factsguide: society now #motivation

In [12]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [13]:
def remove_punctuation(text):
    punctuations =string.punctuation
    return text.translate(str.maketrans('','',punctuations))

In [14]:
df['clean_text']=df['clean_text'].apply(lambda x: remove_punctuation(x))

In [15]:
df.head()

,tweet,clean_text
0,@user when a father is dysfunctional and is s...,user when a father is dysfunctional and is so...
1,@user @user thanks for #lyft credit i can't us...,user user thanks for lyft credit i cant use ca...
2,bihday your majesty,bihday your majesty
3,#model i love u take with u all the time in ...,model i love u take with u all the time in u...
4,factsguide: society now #motivation,factsguide society now motivation

In [16]:
from nltk.corpus import stopwords
" , ".join(stopwords.words('english'))

"a , about , above , after , again , against , ain , all , am , an , and , any , are , aren , aren't , as , at , be , because , been , before , being , below , between , both , but , by , can , couldn , couldn't , d , did , didn , didn't , do , does , doesn , doesn't , doing , don , don't , down , during , each , few , for , from , further , had , hadn , hadn't , has , hasn , hasn't , have , haven , haven't , having , he , he'd , he'll , her , here , hers , herself , he's , him , himself , his , how , i , i'd , if , i'll , i'm , in , into , is , isn , isn't , it , it'd , it'll , it's , its , itself , i've , just , ll , m , ma , me , mightn , mightn't , more , most , mustn , mustn't , my , myself , needn , needn't , no , nor , not , now , o , of , off , on , once , only , or , other , our , ours , ourselves , out , over , own , re , s , same , shan , shan't , she , she'd , she'll , she's , should , shouldn , shouldn't , should've , so , some , such , t , than , that , that'll , the , their , theirs , them , themselves , then , there , these , they , they'd , they'll , they're , they've , this , those , through , to , too , under , until , up , ve , very , was , wasn , wasn't , we , we'd , we'll , we're , were , weren , weren't , we've , what , when , where , which , while , who , whom , why , will , with , won , won't , wouldn , wouldn't , y , you , you'd , you'll , your , you're , yours , yourself , yourselves , you've"

In [17]:
STOPWORDS= set(stopwords.words('english'))

def remove_stopwords(text):
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])

In [18]:
df['clean_text']=df['clean_text'].apply(lambda x: remove_stopwords(x))

In [19]:
df.head()

,tweet,clean_text
0,@user when a father is dysfunctional and is s...,user father dysfunctional selfish drags kids d...
1,@user @user thanks for #lyft credit i can't us...,user user thanks lyft credit cant use cause do...
2,bihday your majesty,bihday majesty
3,#model i love u take with u all the time in ...,model love u take u time urð± ðððð...
4,factsguide: society now #motivation,factsguide society motivation

In [20]:
from collections import Counter
word_count=Counter()

for text in df['clean_text']:
    for word in text.split():
        word_count[word]+=1

word_count.most_common(10)

[('user', 17473),
 ('love', 2647),
 ('day', 2198),
 ('happy', 1663),
 ('amp', 1582),
 ('im', 1139),
 ('u', 1136),
 ('time', 1110),
 ('life', 1086),
 ('like', 1042)]

In [21]:
FREQUENT_WORDS = set(word for (word, wc) in word_count.most_common(3))


def remove_freq_words(text):
    return " ".join([word for word in str(text).split() if word not in FREQUENT_WORDS])

In [22]:
df.head()

,tweet,clean_text
0,@user when a father is dysfunctional and is s...,user father dysfunctional selfish drags kids d...
1,@user @user thanks for #lyft credit i can't us...,user user thanks lyft credit cant use cause do...
2,bihday your majesty,bihday majesty
3,#model i love u take with u all the time in ...,model love u take u time urð± ðððð...
4,factsguide: society now #motivation,factsguide society motivation

In [23]:
RARE_WORDS= set(word for (word,wc) in word_count.most_common()[:-10-1:-1])
RARE_WORDS

{'airwaves',
 'bern',
 'carnt',
 'chisolm',
 'ibizabringitonmallorcaholidayssummer',
 'isz',
 'mantle',
 'shirley',
 'youuuð\x9f\x98\x8dð\x9f\x98\x8dð\x9f\x98\x8dð\x9f\x98\x8dð\x9f\x98\x8dð\x9f\x98\x8dð\x9f\x98\x8dð\x9f\x98\x8dð\x9f\x98\x8dâ\x9d¤ï¸\x8f',
 'ð\x9f\x99\x8fð\x9f\x8f¼ð\x9f\x8d¹ð\x9f\x98\x8eð\x9f\x8eµ'}

In [24]:
def remove_rare_words(text):
    return " ".join([word for word in str(text).split() if word not in RARE_WORDS])

In [25]:
df['clean_text']=df['clean_text'].apply(lambda x: remove_rare_words(x))

In [26]:
df.head()

,tweet,clean_text
0,@user when a father is dysfunctional and is s...,user father dysfunctional selfish drags kids d...
1,@user @user thanks for #lyft credit i can't us...,user user thanks lyft credit cant use cause do...
2,bihday your majesty,bihday majesty
3,#model i love u take with u all the time in ...,model love u take u time urð± ðððð...
4,factsguide: society now #motivation,factsguide society motivation

In [27]:
import re

def remove_spl_char(text):
    text= re.sub('[^A-Za-z0-9]+',' ',text)
    text= re.sub('\s+',' ',text)
    return text

In [28]:
df['clean_text']=df['clean_text'].apply(lambda x: remove_spl_char(x))

In [29]:
df.head()

,tweet,clean_text
0,@user when a father is dysfunctional and is s...,user father dysfunctional selfish drags kids d...
1,@user @user thanks for #lyft credit i can't us...,user user thanks lyft credit cant use cause do...
2,bihday your majesty,bihday majesty
3,#model i love u take with u all the time in ...,model love u take u time ur
4,factsguide: society now #motivation,factsguide society motivation

In [30]:
from nltk.stem.porter import PorterStemmer

ps =PorterStemmer()

In [31]:
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [32]:
df['stemmed_text']=df['clean_text'].apply(lambda x: stem_words(x))

In [33]:
df.head()

,tweet,clean_text,stemmed_text
0,@user when a father is dysfunctional and is s...,user father dysfunctional selfish drags kids d...,user father dysfunct selfish drag kid dysfunct...
1,@user @user thanks for #lyft credit i can't us...,user user thanks lyft credit cant use cause do...,user user thank lyft credit cant use caus dont...
2,bihday your majesty,bihday majesty,bihday majesti
3,#model i love u take with u all the time in ...,model love u take u time ur,model love u take u time ur
4,factsguide: society now #motivation,factsguide society motivation,factsguid societi motiv

In [34]:
from nltk import pos_tag
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer

lemmatizer=WordNetLemmatizer()

wordnet_map={"N":wordnet.NOUN, "V":wordnet.VERB, "R":wordnet.ADV, "J":wordnet.ADJ}

In [35]:
def lemmatize_words(text):

    pos_text=pos_tag(text.split())
    return " ".join([lemmatizer.lemmatize(word, wordnet_map.get(pos[0], wordnet.NOUN)) for word, pos in pos_text])

In [36]:
wordnet.NOUN

'n'

In [37]:
df['lemmatized_text']=df['clean_text'].apply(lambda x: lemmatize_words(x))

In [38]:
df.head()

,tweet,clean_text,stemmed_text,lemmatized_text
0,@user when a father is dysfunctional and is s...,user father dysfunctional selfish drags kids d...,user father dysfunct selfish drag kid dysfunct...,user father dysfunctional selfish drag kid dys...
1,@user @user thanks for #lyft credit i can't us...,user user thanks lyft credit cant use cause do...,user user thank lyft credit cant use caus dont...,user user thanks lyft credit cant use cause do...
2,bihday your majesty,bihday majesty,bihday majesti,bihday majesty
3,#model i love u take with u all the time in ...,model love u take u time ur,model love u take u time ur,model love u take u time ur
4,factsguide: society now #motivation,factsguide society motivation,factsguid societi motiv,factsguide society motivation

In [43]:
df.sample(frac=1).head(15)

,tweet,clean_text,stemmed_text,lemmatized_text
9898,so nice to be able too see both. q #gpeurope #...,nice able see q gpeurope baku sta lemans lm16 ...,nice abl see q gpeurop baku sta leman lm16 rac...,nice able see q gpeurope baku sta lemans lm16 ...
7052,"everyone in india know that #bjp , politicia...",everyone india know bjp politicians involved d...,everyon india know bjp politician involv drug ...,everyone india know bjp politician involve dru...
6854,fathers day#come on fattyð¬ð§,fathers daycome fatty,father daycom fatti,father daycome fatty
29462,@user .@user because everyones life is a cons...,user user everyones life constant persuit happ...,user user everyon life constant persuit happi ...,user user everyones life constant persuit happ...
19854,@user hoping everyone is having a weekend fil...,user hoping everyone weekend filled memorable ...,user hope everyon weekend fill memor experi sa...,user hop everyone weekend fill memorable exper...
19405,@user @user @user sad you're lovely girl,user user user sad youre lovely girl,user user user sad your love girl,user user user sad youre lovely girl
2110,what the heck this is so mean!!! please silen...,heck mean please silence racism bully,heck mean pleas silenc racism bulli,heck mean please silence racism bully
30986,glo on ðð¡ #pool #poolday #summer #tan #f...,glo pool poolday summer tan fitness fit athlet...,glo pool poolday summer tan fit fit athlet sun...,glo pool poolday summer tan fitness fit athlet...
17112,@user school why u do dis? :( #school #ugh #w...,user school u dis school ugh teen girls guys,user school u di school ugh teen girl guy,user school u dis school ugh teen girl guy
29537,.@user (&amp; the #media constantly repeating ...,user amp media constantly repeating ushered un...,user amp media constantli repeat usher unfoun ...,user amp medium constantly repeat ushered unfo...
589,who would steal awork from @user #boohiss,would steal awork user boohiss,would steal awork user boohiss,would steal awork user boohiss
30038,annadayð¯ð« #yurika #anna #anriri #shinjuk...,annaday yurika anna anriri shinjuku karaoke di...,annaday yurika anna anriri shinjuku karaok din...,annaday yurika anna anriri shinjuku karaoke di...
13674,officially old now i've staed paying my studen...,officially old ive staed paying student loan b...,offici old ive sta pay student loan back,officially old ive staed pay student loan back
22988,just stop guns. on a watch list and still mana...,stop guns watch list still manages purchase mi...,stop gun watch list still manag purchas milita...,stop gun watch list still manage purchase mili...
313,7 horribly ads from #2016 that made us cringe,7 horribly ads 2016 made us cringe,7 horribl ad 2016 made us cring,7 horribly ad 2016 make u cringe

In [44]:
text="https://www.hackersrealm.net is the URL of the channel Hackers Realm"

In [45]:
def remove_url(text):
    return re.sub(r'http\S+|www\S+','',text)

In [46]:
df['clean_text']=df['clean_text'].apply(lambda x: remove_url(x))

In [47]:
def remove_html_tags(text):
    return re.sub(r'<.*?>', '', text)

In [48]:
df['clean_text']=df['clean_text'].apply(lambda x: remove_html_tags(x))

In [49]:
pip install pyspellchecker

Collecting pyspellchecker
  Downloading pyspellchecker-0.8.2-py3-none-any.whl.metadata (9.4 kB)
Downloading pyspellchecker-0.8.2-py3-none-any.whl (7.1 MB)
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.1 MB ? eta -:--:--
   ------- -------------------------------- 1.3/7.1 MB 4.5 MB/s eta 0:00:02
   ---------------- ----------------------- 2.9/7.1 MB 6.2 MB/s eta 0:00:01
   ------------------------ --------------- 4.5/7.1 MB 6.4 MB/s eta 0:00:01
   ----------------------------------- ---- 6.3/7.1 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 7.1/7.1 MB 7.2 MB/s eta 0:00:00
Installing collected packages: pyspellchecker
Successfully installed pyspellchecker-0.8.2
Note: you may need to restart the kernel to use updated packages.